name: 'susi'
version: 0.1.0
description: A SUSI client written in dart.
author: Tino Rusch <tino.rusch@gmail.com>
homepage: https://github.com/trusch/susi-dart
dependencies:
  uuid: ">=0.5.0 <0.6.0"

